export const SONG_OF_THE_DAY = [
    {"number": "1", "title": "The Morning Breaks", "url": "https://www.churchofjesuschrist.org/media/music/songs/the-morning-breaks?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/1b/13/1b13523680a0201653cfc366afbef38cde7fe1aa/the_morning_breaks_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "1", "title": "The Morning Breaks", "url": "https://www.churchofjesuschrist.org/media/music/songs/the-morning-breaks?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/1b/13/1b13523680a0201653cfc366afbef38cde7fe1aa/the_morning_breaks_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "215", "title": "Ring Out, Wild Bells", "url": "https://www.churchofjesuschrist.org/media/music/songs/ring-out-wild-bells?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/11/c9/11c9d260930a2ac7b0f41a17c95458b0dc147c5f/ring_out_wild_bells_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "217", "title": "Come, Let Us Anew", "url": "https://www.churchofjesuschrist.org/media/music/songs/come-let-us-anew?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/fc/01/fc012ef8e282803f0d1d3813fbac9673e6e5ea35/come_let_us_anew_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "164", "title": "I Will Follow God's Plan", "url": "https://www.churchofjesuschrist.org/media/music/songs/i-will-follow-gods-plan?crumbs=childrens-songbook&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/7a/53/7a5338f1758b7390ed159040a948d9950f32e6d4/i_will_follow_gods_plan_vocal_accompaniment_eng.mp3", "book":"CHILDREN'S"},
    {"number": "14", "title": "Sweet Is the Peace the Gospel Brings", "url": "https://www.churchofjesuschrist.org/media/music/songs/sweet-is-the-peace-the-gospel-brings?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/a7/1d/a71d27a6e362f6f57ab3d61c7f16df2ed9a66488/sweet_is_the_peace_the_gospel_brings_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "169", "title": "As Now We Take the Sacrament", "url": "https://www.churchofjesuschrist.org/media/music/songs/as-now-we-take-the-sacrament?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/3d/00/3d0020c7d785b2bfd12019f6de76df54b4c62bbb/as_now_we_take_the_sacrament_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "21", "title": "Come, Listen to a Prophet's Voice", "url": "https://www.churchofjesuschrist.org/media/music/songs/come-listen-to-a-prophets-voice?crumbs=hymns&lang=eng", "mp3_url": "https://assets.churchofjesuschrist.org/35/9e/359e99b03493c6422cdce5a0a2fc530ef8d22b3d/come_listen_to_a_prophets_voice_vocal_accompaniment_eng.mp3", "book":"HYMNAL"},
    {"number": "264", "title": "Hark, All Ye Nations!", "url": "https://www.churchofjesuschrist.org/media/music/songs/hark-all-ye-nations?crumbs=hymns&lang=eng", "mp3_url": "https://media2.ldscdn.org/assets/music/hymns/2001-01-2640-hark-all-ye-nations-vocal-and-instrumental-192k-eng.mp3", "book":"HYMNAL"},
]